Zodiac CRRC Modifications
fire-391/3dMP pull request #25
Opened 2024-01-07 07:24 UTC by Zycorge

Creates a stage for future boats/watercraft.
Creates a new class from the base NATO Assault Craft which is called MRB Zodiac which will show up under the 3d MRB Faction.

Increased MaxSpeed and EnginePower. This is an attempt to reflect zodiac speeds based on what I could determine from watching videos of them and using watercraft weight/horsepower calculations for the available specs for the CRRC. Those work out to suggest its top speed should be between 40 & 50 kph. After testing 50 feels way to quick. 

Max Speed in game is now ~40 - 45 kph which feels appropriately quick for the zodiac.

2024-01-07 07:26 UTC, Zycorge commented
I'll also note that I tested this as a standalone mod with only a config.cpp file. Read through the way we have 3d_Assets laid out and then modified the code to fit that. Hopefully, its integrated correctly.

2024-01-07 22:32 UTC, fire-391 commented
Please place your new vehicle config in https://github.com/fire-391/3dMP/blob/master/3d_Assets/cfgVehicles/cfgGround.hpp 
and give it scope and faction params so it actually shows up in editor/Zeus.

2024-01-08 00:41 UTC, Zycorge commented
I think I did that correctly?

2024-01-08 23:43 UTC, fire-391 requested changes

2024-01-08 23:43 UTC, fire-391 commented on 3d_Assets/cfgVehicles/cfgGround.hpp
> +		editorSubcategory = "B_3d_Marine_Raider_Vehicles";
```suggestion
		editorSubcategory = "B_3d_Marine_Raider_Watercraft";

```

2024-01-08 23:43 UTC, fire-391 commented on 3d_Assets/cfgVehicles/cfgGround.hpp
> +		crew = "MRB_Element_CSO";
```suggestion
		crew = "MRB_Element_CSO";
                displayName = "MRB Zodiac";

```

2024-01-08 23:45 UTC, fire-391 commented
Also need to add "MRB_Zodiac"; to https://github.com/fire-391/3dMP/blob/master/3d_Assets/config.cpp under units

2024-01-10 01:25 UTC, fire-391 approved these changes

2024-01-10 01:25 UTC, merged